### PR TITLE
Redefine protocol

### PR DESCRIPTION
**Pull request by joaobrittoneto**
Define a packet as carrying a generic bunch of data.
Let the meaning of data be handle by someone else (eg: protobuf).

### CODE REVIEW

**Comment by joaobrittoneto** [comment]
@doudou,
I'm redefining this protocol as just `<Header><Size><Data><CheckSum>`.
The `<Data>` will be handled by protobuf.
Do you see any other field that may goes here

**Comment by doudou** [comment]
I kind of like the packet counter (packet ID). Does the USBL give some information on packet loss (or do you have other means to detect packet loss ?)

I would reduce it to 16 bit though and have a tiny bit of logic for wraparounds in the driver.

**Comment by joaobrittoneto** [comment]
I removed the packet ID in order to simplify the protocol. I realized two minors problems with it: 
i) A  boundary condition was missing, and I was not sure how to handle it.
ii) The lack of sync between the local and remote side could count for multiples loss. 

From the remote side point of view, the packet ID would be the best way to check for loss of consecutive packets (ignoring the lack of sync thing).
From the local side point of view, the usbl provides an ack for every byte [delivered](https://github.com/Brazilian-Institute-of-Robotics/drivers-usbl_evologics/blob/master/src/DriverTypes.hpp#L411). I think that count bytes ack and comparing with the packet sent may be used for verify packets delivered (not really the same as the packet loss)

I can came back with the Packet ID if you think the minors problems are not really a problem.

**Comment by doudou** [comment]
There's another potential problem actually: out-of-order delivery. It is possible with the USBL AFAIK.

Do all the channels mandate an acknowledgment ?

**Comment by joaobrittoneto** [comment]
Damn, you are right. The virtual channels (multiples interfaces) was one of the usbl's complexity that I didn't really explore. 

The ack is for the overall data delivered. It does not take in account the channel.
So, it's pretty hard to track a packet in the delivered raw data ack (channel issue and also to identify where in the usbl's buffer is the packet).

I came back to the packet ID. Later on we can figure out how to handle the out of sync/ boundary condition.

**Comment by joaobrittoneto** [comment]
Done. Packet ID is back

**Comment by doudou** [comment]
Looks good to me

**Pull request merged**
